repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: fix-encoding-pragma
  - id: pretty-format-json
  - id: check-json

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.10.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.3.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
