version: '3'
services:
  app:
    container_name: matemaquest
    image: marcorfilacarreras/matemaquest:latest
    ports:
    - 8080:8080
    environment:
    - ENVIRONMENT=production
    - LIBSQL_URL=${LIBSQL_URL}
    - LIBSQL_TOKEN=${LIBSQL_TOKEN}
    - BASE_URL=${BASE_URL}
    links:
    - radian:radian
    restart: always

  radian:
    container_name: radian
    image: radian
    ports:
    - 2112:2112
    volumes:
    - ~/data:/data
    restart: always
