version: '3'
services:
  app:
    container_name: matemaquest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    environment:
    - ENVIRONMENT=production
    - LIBSQL_URL=${LIBSQL_URL}
    - LIBSQL_TOKEN=${LIBSQL_TOKEN}
    restart: always
