version: '3'
services:
  app:
    container_name: matemaquest
    image: marcorfilacarreras/matemaquest:latest
    ports:
    - 8080:8080
    environment:
    - ENVIRONMENT=production
    - LIBSQL_URL=${LIBSQL_URL}
    - LIBSQL_TOKEN=${LIBSQL_TOKEN}
    - BASE_URL=${BASE_URL}
    - REDIS_URL=${REDIS_URL}
    - REDIS_PORT=${REDIS_PORT}
    links:
    - radian:radian
    - redis:redis
    restart: always

  radian:
    container_name: radian
    image: radian
    ports:
    - 2112:2112
    volumes:
    - ~/data:/data
    restart: always

  redis:
    container_name: redis
    image: redis
    ports:
    - 6379:6379
    restart: always
