name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: Get new Docker Image
      run: docker pull marcorfilacarreras/matemaquest

    - name: Stop API
      run: docker-compose rm -s -v -f app

    - name: Start containers
      run: docker-compose -f docker-compose.yml --env-file ../../../.env up -d app

    - name: Remove old images
      run: docker image prune -f
