name: Test

on:
  push:
    branches:
    - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: temurin
        architecture: x64

    - name: Build with Maven
      run: mvn clean package
      env:
        LIBSQL_URL: ${{ secrets.LIBSQL_URL }}
        LIBSQL_TOKEN: ${{ secrets.LIBSQL_TOKEN }}
        BASE_URL: ${{ secrets.BASE_URL }}

  docker:
    needs: [test]
    uses: marcorfilacarreras/matemaquest/.github/workflows/docker.yml@master
    secrets: inherit

  deploy:
    needs: [test, docker]
    uses: marcorfilacarreras/matemaquest/.github/workflows/deploy.yml@master
